### ISSUE TITLE
API endpoint to mind certificates ?

### ISSUE THREAD

**Issue by 0123hoang** [spiffe/tornjak#45]
Is there any API end point to mint certificates (instead of cli ./bin/spire-server mint x509...)?

**Comment by lumjjb** [comment]
Right now we don’t have something that does this in the Tornjak interface. Part of the reason is that the minted certs should only be accessible via the workload. However, there is an SPIFFE helper (https://github.com/spiffe/spiffe-helper) which may be of interest to you here!

Is there a specific usecase that you are thinking about? If there is a good usecase, we can take a look at it!

**Comment by 0123hoang** [comment]
I want SPIRE server can be a generate-certificate server, distribute it to edge service, stay away from trusting chain manage but can isolate each other. Have a pair SPIRE agent + SPIRE helper in each service is a option, but this require a bit more complicate and network.

Thank you for reply. Maybe I'm trying to call directly to server socket by grpc api.
