### ISSUE TITLE
Securing Tornjak with Keycloak

### ISSUE THREAD

**Issue by mamy-CS** [spiffe/tornjak#63]
- We are looking for feedback on how we will integrate Keycloak as a user management tool with Tornjak.

Referencing - https://github.com/spiffe/tornjak/issues/61

### Specific plan details for Tornjak React Front-End and GO Back-End
- [x] One Client configured in Keycloak - Frontend communicates with public client under the Tornjak realm
- [x] Frontend client has public access since it just needs to log in and redirect to a valid URI after successful login (Turn off client Authentication under clients settings - When it's ON, the OIDC type is set to confidential access type. When it's OFF, it is set to public access type)
- [x] Backend receives a bearer-only token included in the request and it never initiates login on its own.
- [x] Realm roles and client roles assigned and mapped for tornjak public client 
- [x] Roles embedded with the JWT Token through Keycloak configuration, now we can get the client roles from the JWT token with the “roles” key.
- [x] Initially user sees the Keycloak login page
- [x] User tries to log in to the front-end react application
- [x] User will be redirected to the Keycloak server for authentication.
- [x] If authentication is successful, Authenticated user will be redirected to the Tornjak application. At the same time, the user will get a JWT (JSON Web Token).
- [x] Send the token as a header to the back-end with the request 
- [x] Unauthenticated users will be redirected back to the Keycloak login page.
- [x] With the valid token, the front-end can access the back-end GO rest API by sending the token along with the service request.
- [x] At every request sent, the request will be intercepted to check token validity. If expired, the token will be refreshed by communicating with keycloak and the updated token will be sent to the backend with the request.
- [x] Back-end will validate the token with a public key from keycloak
- [x] Back-end will check specified role for the user
- [x] Back-end will make APIs accessible based upon the specific roles (Admin or Viewer)
- [x] If the token is valid, the back-end will serve the request accordingly.
- [x] If the token is invalid, the back-end will respond with error code 401 (Unauthorized) or 403 (forbidden) for a specific role. 
- [x] Logout - redirected back to key cloak login page

**Comment by maia-iyer** [comment]
@mamy-CS It might also be important to consider the logic of expiring tokens which may require using refresh token? I'm unsure how the logic would work there, although it is likely a frontend issue, as the backend only needs to respond that the token is expired.

**Comment by maia-iyer** [comment]
We are looking for feedback on how we will integrate Keycloak as a user management tool with Tornjak. 

**Proposed Oath2-inspired Protocol**
We propose the following protocol of single sign-on and resource access via JWT access tokens. 
- Single sign-on involves redirect the user to Keycloak login to obtain an JWT used to request to the Tornjak backend. 
![sso](https://user-images.githubusercontent.com/30640956/186240483-02e58c6a-a6de-4bc5-8dcb-10701ef7e800.png)
- Resource Access involves the use of the JWT obtained during single sign-on to make requests to the Tornjak backend. 
![rap](https://user-images.githubusercontent.com/30640956/186243338-7794a40b-7062-4bb9-86ae-fef1c3812313.png)



In order to set this up, we would need to configure Keycloak such that the Tornjak frontend and backend are each a client applications under one Keycloak realm. 

---

**Implementation of Authorization**
Currently, we are looking to create two user roles and allow two levels of access to resources:
- Viewer: may view and download information on all resources
- Admin: may view and download information, but also may create and manage clusters and spire entities

There are two ways we can implement the authorization of this logic. 
- **Application-level implementation of authorization:** 
    - Tornjak backend receives a request, and calls Keycloak to verify a sent JWT access token
    - Keycloak authenticates and sends back the name of the role associated with the user
    - Tornjak responds based on the role name and request. Because of our pre-defined two-level access logic, this is easily implementable
- **Keycloak-level implementation of authorization:**
    - Tornjak backend receives a request, and calls Keycloak to verify a sent JWT access token
    - Keycloak authenticates, and checks logic implemented internally that a user may access a certain API
    - Tornjak receives Keycloak authentication and authorization, and performs request based solely on Keycloak response, not role

Pros of the former method:
- The logic is wrapped in Tornjak itself, and makes setup or learning Tornjak easier
- There is a potentially easy workaround down the line if one wants more granularity with authorization protocols. 

Pros of the latter method:
- There is more flexibility overall in implementing more complicated authorization policies in the long run
- While this requires more work to configure, Keycloak offers ways to import and export authorization configs, which perhaps it would be useful for us to look into and provide

---

**Feedback requested:**
Some specific questions we would like feedback or suggestions on: 
- Is there significant benefit/drawback in implementing the authorization protocol listed above differently? Perhaps there is a way that can give more control over direct SPIRE entities?
- More generally, what kind of granularity might we want in a resource management plane of SPIRE?
